Repository yarogono/DungeonEleven, pull requests merged in 2023-10, with the labels that each got.

#24 Feature/#23 CustomSingleton
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Managers/ResourceManager.cs
  Client/Assets/Scripts/Packet/GenPackets.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/ServerSession.cs
  Client/Assets/Scripts/Utils/CustomSingleton.cs
  Client/Assets/Scripts/Utils/CustomSingleton.cs.meta
  Client/Assets/Scripts/Utils/Define.cs
  Client/Assets/Scripts/Utils/PacketQueue.cs
Labels: Feature

#25 Feature/#22 DataManager
  Client/Assets/Resources/Data/ItemData.json
  Client/Assets/Resources/Data/ItemData.json.meta
  Client/Assets/Scripts/DataFormat.meta
  Client/Assets/Scripts/DataFormat/Item.cs
  Client/Assets/Scripts/DataFormat/Item.cs.meta
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Managers/DataManager.cs.meta
Labels: Feature

#26 Feature/#20 SoundManager
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/Managers/SoundManager.cs.meta
Labels: Feature

#27 Feature/#20 SoundManager (Defin enum 클래스 추가)
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/Managers/SoundManager.cs.meta
Labels: Feature

#28 Feature/#20 SoundManager(Enum 추가 후 다시 머지)
  Client/Assets/Scripts/Utils/Define.cs
Labels: Feature

#30 Feature/#29 SoundManager
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/Managers/SoundManager.cs.meta
Labels: Feature

#37 UI/ResultUI 구성
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scenes/DungeonTempScene.unity
Labels: UI

#39 Feature/GameManager DungeonTimer
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
Labels: Feature

#41 Feature/SoundManager BGM파일 추가
  Client/Assets/Resources/Sounds/Boss.mp3
  Client/Assets/Resources/Sounds/Boss.mp3.meta
  Client/Assets/Resources/Sounds/coin.mp3
  Client/Assets/Resources/Sounds/coin.mp3.meta
  Client/Assets/Resources/Sounds/dungeon.mp3
  Client/Assets/Resources/Sounds/dungeon.mp3.meta
  Client/Assets/Resources/Sounds/dungeon2.mp3
  Client/Assets/Resources/Sounds/dungeon2.mp3.meta
  Client/Assets/Resources/Sounds/start.mp3
  Client/Assets/Resources/Sounds/start.mp3.meta
  Client/Assets/Scripts/Managers/SoundManager.cs
Labels: Feature

#42 Feature/#38
  Client/Assets/Animations/Monsters.meta
  Client/Assets/Animations/Monsters/EvilSlimeSprite.controller
  Client/Assets/Animations/Monsters/EvilSlimeSprite.controller.meta
  Client/Assets/Animations/Monsters/EvilSlime_Idle.anim
  Client/Assets/Animations/Monsters/EvilSlime_Idle.anim.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/Player.png.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/PlayerV2.png.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/PlayerV3.png.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/Slime.png.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/SlimeV2.png.meta
  Client/Assets/Resources/Externals/Mini_Dungeon_v1.0/Mini_Dungeon_v1.0/Characters/Wizard.png.meta
  Client/Assets/Resources/Externals/Slime/Idle/Idle01.png.meta
  Client/Assets/Resources/Externals/Slime/Idle/Idle02.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump01.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump02.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump03.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump04.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump05.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump06.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump07.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump08.png.meta
  Client/Assets/Resources/Externals/Slime/Jump/Jump09.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep01.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep02.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep03.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep04.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep05.png.meta
  Client/Assets/Resources/Externals/Slime/Sleep/Sleep06.png.meta
  Client/Assets/Resources/Externals/Slime/Walk/walk01.png.meta
  Client/Assets/Resources/Externals/Slime/Walk/walk02.png.meta
  Client/Assets/Resources/Externals/Slime/Walk/walk03.png.meta
  Client/Assets/Resources/Externals/Slime/Walk/walk04.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin01.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin02.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin03.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin04.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin05.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin06.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin07.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin08.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin09.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin10.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin11.png.meta
  Client/Assets/Resources/Externals/Slime/spin/Spin12.png.meta
  Client/Assets/Scenes/MonsterTempScene.unity
  Client/Assets/Scenes/MonsterTempScene.unity.meta
  Client/Assets/Scripts/Controllers/MonsterController.cs
  Client/Assets/Scripts/Controllers/MonsterController.cs.meta
  Client/Assets/Scripts/Controllers/MonsterDamageController.cs
  Client/Assets/Scripts/Controllers/MonsterDamageController.cs.meta
  Client/Assets/Scripts/Entities/PlayerDetector.cs
  Client/Assets/Scripts/Entities/PlayerDetector.cs.meta
  Client/ProjectSettings/TagManager.asset
Labels: Feature

#44 Feature/ItemManager
  Client/Assets/Resources/Data/ItemData.json
  Client/Assets/Resources/Prefabs/Items.meta
  Client/Assets/Resources/Prefabs/Items/Accessories.prefab
  Client/Assets/Resources/Prefabs/Items/Accessories.prefab.meta
  Client/Assets/Resources/Prefabs/Items/Armor.prefab
  Client/Assets/Resources/Prefabs/Items/Armor.prefab.meta
  Client/Assets/Resources/Prefabs/Items/Potion.prefab
  Client/Assets/Resources/Prefabs/Items/Potion.prefab.meta
  Client/Assets/Resources/Prefabs/Items/Weapon.prefab
  Client/Assets/Resources/Prefabs/Items/Weapon.prefab.meta
  Client/Assets/Scripts/Controllers/ItemController.cs
  Client/Assets/Scripts/Controllers/ItemController.cs.meta
  Client/Assets/Scripts/Controllers/MonsterController.cs
  Client/Assets/Scripts/DataFormat/Item.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Managers/ItemManager.cs
  Client/Assets/Scripts/Managers/ItemManager.cs.meta
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Utils/Define.cs
  Server/PacketGenerator/PacketFormat.cs
Labels: Feature

#50 Refactor/#49 MP3파일 WAV로 변환
  Client/Assets/Resources/Sounds/Boss.mp3
  Client/Assets/Resources/Sounds/Boss.mp3.meta
  Client/Assets/Resources/Sounds/Boss.wav.meta
  Client/Assets/Resources/Sounds/coin.mp3
  Client/Assets/Resources/Sounds/coin.mp3.meta
  Client/Assets/Resources/Sounds/coin.wav
  Client/Assets/Resources/Sounds/coin.wav.meta
  Client/Assets/Resources/Sounds/dungeon.mp3
  Client/Assets/Resources/Sounds/dungeon.mp3.meta
  Client/Assets/Resources/Sounds/dungeon.wav.meta
  Client/Assets/Resources/Sounds/dungeon2.mp3
  Client/Assets/Resources/Sounds/dungeon2.mp3.meta
  Client/Assets/Resources/Sounds/dungeon2.wav.meta
  Client/Assets/Resources/Sounds/start.mp3
  Client/Assets/Resources/Sounds/start.mp3.meta
  Client/Assets/Resources/Sounds/start.wav.meta
Labels: Refactor

#53 Feature/#51 GameManager 시작 Player 상태 관리
  Client/Assets/Scripts/Controllers/PlayerInfo.cs
  Client/Assets/Scripts/Controllers/PlayerInfo.cs.meta
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/GenPackets.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Common/Packet/ClientPacketManager.cs
  Common/Packet/GenPackets.cs
  Common/Packet/ServerPacketManager.cs
  Server/.gitignore
  Server/DummyClient/Packet/ClientPacketManager.cs
  Server/DummyClient/Packet/GenPackets.cs
  Server/PacketGenerator/PDL.xml
  Server/Server/GameRoom.cs
  Server/Server/Packet/GenPackets.cs
  Server/Server/Packet/PacketHandler.cs
  Server/Server/Packet/ServerPacketManager.cs
  Server/Server/Server.csproj
  Server/Server/Utils/FileIO.cs
Labels: Feature

#54 Player bug fix
  Client/Assets/Animations/MainSprite.controller
  Client/Assets/Resources/Prefabs/Maps/BossMap.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap0.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap1.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap2.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap3.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap4.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap5.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap6.prefab
  Client/Assets/Resources/Prefabs/Maps/OutOfDungeonLine.prefab
  Client/Assets/Resources/Prefabs/Maps/OutOfDungeonLine.prefab.meta
  Client/Assets/Resources/Prefabs/Maps/SideMap0.prefab
  Client/Assets/Resources/Prefabs/Maps/SideMap1.prefab
  Client/Assets/Resources/Prefabs/Maps/SideMap2.prefab
  Client/Assets/Resources/Prefabs/Maps/SideMap3.prefab
  Client/Assets/Resources/Prefabs/Maps/StartMap.prefab
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Resources/Prefabs/Player.prefab.meta
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scenes/MonsterTempScene.unity
  Client/Assets/Scripts/Controllers/MovementController.cs
  Client/Assets/Scripts/Controllers/PlayerController.cs
  Client/Assets/Scripts/Entities/OutOfDungeon.cs
  Client/Assets/Scripts/Entities/OutOfDungeon.cs.meta
  Client/Assets/Scripts/Managers/MapManager.cs
Labels: Fix

#56 Feature/UI/StoreScene
  Client/Assets/Resources/Externals/UI/2D Casual Game UI HD/Sprite/popup elements.png.meta
  Client/Assets/Resources/Prefabs/UI/Slot.prefab
  Client/Assets/Scenes/StoreScene.unity
  Client/Assets/Scripts/Managers/UIManager.cs
  Client/Assets/Scripts/Managers/UIManager.cs.meta
  Client/Assets/Scripts/UIs/SlotDragHandler.cs
  Client/Assets/Scripts/UIs/SlotDragHandler.cs.meta
  Client/Assets/Scripts/UIs/SortingButtonHandler.cs
  Client/Assets/Scripts/UIs/SortingButtonHandler.cs.meta
  Client/Assets/Scripts/UIs/TributeButton.cs
  Client/Assets/Scripts/UIs/TributeButton.cs.meta
  Client/Assets/Scripts/UIs/UIBase.cs
  Client/Assets/Scripts/UIs/UIBase.cs.meta
  Client/Assets/Scripts/UIs/UIDayAndGold.cs
  Client/Assets/Scripts/UIs/UIDayAndGold.cs.meta
  Client/Assets/Scripts/UIs/UISellingResult.cs
  Client/Assets/Scripts/UIs/UISellingResult.cs.meta
  Client/Assets/Scripts/UIs/UISlot.cs
  Client/Assets/Scripts/UIs/UISlot.cs.meta
  Client/Assets/Scripts/UIs/UISlots.cs
  Client/Assets/Scripts/UIs/UISlots.cs.meta
  Client/Assets/Scripts/UIs/UIStore.cs
  Client/Assets/Scripts/UIs/UIStore.cs.meta
  Client/Assets/Scripts/UIs/UIStoreScene.cs
  Client/Assets/Scripts/UIs/UIStoreScene.cs.meta
  Client/Assets/Scripts/UIs/UITribute.cs
  Client/Assets/Scripts/UIs/UITribute.cs.meta
  Client/Assets/Scripts/UIs/UpgradeButtonHandler.cs
  Client/Assets/Scripts/UIs/UpgradeButtonHandler.cs.meta
Labels: Feature, UI

#59 Refacotr/#58 Item 프리팹 파일명 수정 및 ItemData json 수정
  Client/Assets/Resources/Data/ItemData.json
  Client/Assets/Resources/Prefabs/Items/Accessory.prefab
  Client/Assets/Resources/Prefabs/Items/Accessory.prefab.meta
  Client/Assets/Resources/Prefabs/Items/Misc.prefab
  Client/Assets/Resources/Prefabs/Items/Misc.prefab.meta
Labels: Refactor

#60 리드미 수정1
  README.md
Labels: Docs

#61 Feature/UI/주석제거
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scenes/StartScene.unity
  Client/Assets/Scenes/StoreScene.unity
  Client/Assets/Scripts/DataFormat/Item.cs
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/Managers/ItemManager.cs
  Client/Assets/Scripts/UIs/TributeButton.cs
  Client/Assets/Scripts/UIs/UIDayAndGold.cs
  Client/Assets/Scripts/UIs/UIPlayerHUD.cs
  Client/Assets/Scripts/UIs/UIPlayerHUD.cs.meta
  Client/Assets/Scripts/UIs/UIStartScene.cs
  Client/Assets/Scripts/UIs/UIStartScene.cs.meta
  Client/Assets/Scripts/UIs/UIStore.cs
  Client/Assets/Scripts/UIs/UITribute.cs
  Client/Assets/Scripts/UIs/UpgradeButtonHandler.cs
  Client/Assets/Scripts/Utils/Define.cs
Labels: Feature, UI

#62 Map, Monsters Bug fix
  Client/Assets/Resources/Prefabs/Maps/MainMap0.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap1.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap2.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap3.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap4.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap5.prefab
  Client/Assets/Resources/Prefabs/Maps/MainMap6.prefab
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scripts/Controllers/MonsterController.cs
  Client/Assets/Scripts/Entities/OutOfDungeon.cs
  Client/Assets/Scripts/Managers/MapManager.cs
  Client/ProjectSettings/TagManager.asset
Labels: Fix

#63 Feature/UI/PlayerHUD 연동
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scripts/Controllers/HealthSystem.cs
  Client/Assets/Scripts/Controllers/MovementController.cs
  Client/Assets/Scripts/Controllers/PlayerInfo.cs
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/UIs/UIPlayerHUD.cs
  Client/Assets/Scripts/UIs/UITribute.cs
Labels: Feature, UI

#64 Feature/UI/DungeonResult 구현
  Client/Assets/Scenes/DungeonScene.unity
  Client/Assets/Scripts/Controllers/PlayerInfo.cs
  Client/Assets/Scripts/Managers/GameManager.cs
  Client/Assets/Scripts/Managers/MapManager.cs
  Client/Assets/Scripts/Managers/UIManager.cs
  Client/Assets/Scripts/UIs/UIDungeonResult.cs
  Client/Assets/Scripts/UIs/UIDungeonResult.cs.meta
  Client/Assets/Scripts/UIs/UIDungeonScene.cs
  Client/Assets/Scripts/UIs/UIDungeonScene.cs.meta
  Client/Assets/Scripts/UIs/UIPlayerHUD.cs
  Client/ProjectSettings/EditorBuildSettings.asset
Labels: Feature, UI
